### ISSUE TITLE
Translation issues

### ISSUE THREAD

**Issue by marcoburato** [Lattyware/massivedecks#111]
Hello, I'm translating the game to Italian and I'm nearly done.
I have found a few issues that I'd like to discuss.

**Pluralization**
The pluralization in English is done by simply appending an "s". But in Italian, pluralization is a bit more complex. Specifically, here are a few relevant examples:

Point = Punto
Points = Punti
White Card = Carta Bianca
White Cards = Carte Bianche

So, I need to pluralize each word and to make the plural I need to change the word itself. Usually, you need to change the last character, but sometimes it's more complex (see Bianca/Bianche).
I see a few possible solutions:
1. Implement a fully featured pluralization function (overkill)
2. Implement a limited pluralization function to handle only needed pluralization rules
3. Implement a pluralization function that uses custom logic to pluralize only the few strings we need (either with a dictionary or hardcoding them)

Thoughts?
For (1) and (2) how would I convert from an MdString to String to analyze it?

**Lobby name**
The lobby name is currently chosen by the server and not localised. It's always "Username's Game".

**Language selection from browser language**
It looks like the code is already supposed to automatically choose the preferred browser language, but it doesn't seem to work.
I'll do some more digging, but can you clarify if the language code should be "It" or "It-IT"?

**Comment by Lattyware** [comment]
Thanks for putting in the work to translate!

The plural issue is certainly a real one. Honestly, if it is complex, the best answer might be to do whatever the equivalent of "card(s)" is (i.e: have one form that may or may not be plural), if that reads even reasonably well in the language. In general, I'd just go for the simplest possible solution for the use case, and expand it if needed (the English version doesn't work generally, e.g: sheep -> sheeps would be wrong, but it is good enough for the game as it stands).

The simplest solution would probably be just to do a case over the singular and hard-code each plural that actually gets used, and default to just using the singular unchanged otherwise. It introduces a potential bug if it isn't updated when a new plural is used, but I can't say it seems worth a huge amount of effort beyond that.

You *could* in theory use `MassiveDecks.Strings.Languages.givenLanguageString` to convert the `singular` `MdString` to a `String`, but that's probably not a great route to go down.

Please do let me know if you want a further hand with the code side of the plural stuff.

On the lobby name, that's a bug and I'll make another issue for fixing that up. At some point it'd be nice to let users change the name as well.

On the language selection, that wasn't well tested so I can believe it doesn't work well right now. 

As to the language code, `it` and `it-IT` should really be considered equivalent, essentially, as Italian as spoken in Italy is what anyone would expect to be the default. The region subtag is only needed where one might not assume that regional dialect is the one in use (e.g: `en-GB` due to the prevalence of American English). Do note it is case sensitive (this may be a little confusing as the case and dashes change depending on Elm code or the IETF language tag itself due to limits for Elm identifiers).

The reality is that we match against what the browser asks for exactly and then just fall back to English. 

In my case, my browser's `navigator.languages` looks like:

    Array(3) [ "en-GB", "en", "en-US" ]

I would expect most browsers to do something similar (asking for your regionally specific preference, then the general case, then anything that is close but maybe not exactly what you want). Of course, some may not and ideally we'd be doing fuzzier matching to try and find the best fit. I'll open a new issue for that (it's actually in the code as a TODO, but it'd be better to surface it here).

**Comment by marcoburato** [comment]
Thanks for the prompt feedback. I have just submitted the pull request.
