### ISSUE TITLE
Translate cards ?

### ISSUE THREAD

**Issue by yoannm57** [Lattyware/massivedecks#116]
Good morning,

In addition to the game or menu is it possible to translate the cards if yes, or is how?

Thank you in advance.

**Comment by Lattyware** [comment]
You can't directly in Massive Decks, because the cards come from an outside source (currently only [Cardcast](https://www.cardcastgame.com/browse), although the game could have other sources supported easily enough), and there are a huge number of decks out there.

In general, you want to just find decks in the language you want to play in. 

The only thing we can really do on this front very usefully would be #110 - changing what deck we recommend to the user to one in the language they are using rather than always the English one. That'll hopefully get added soon when there is a chance.

If the thought was automatic translation for each user of the cards for players using different languages, that's a much harder task. You'd have to have a source of decks that had all the necessary translations for all the cards, which doesn't currently exist. Even then there would be edge cases like custom cards, and issues with things like puns not necessarily translating, so it isn't something I'd plan to attempt.

**Comment by yoannm57** [comment]
Hello, I saw afterwards, thank you.
I'm going to work when I have some time for the "FR" version / translation.
Thanks for your great work ;)

**Comment by Lattyware** [comment]
That would be excellent. I look forward to seeing a pull request! I'll close this issue for now if that covers it, but feel free to open new ones or reopen this one if needed.
