### ISSUE TITLE
Hide white cards when it's your turn

### ISSUE THREAD

**Issue by clidx** [Lattyware/massivedecks#139]
When it's your round, you can still see a list of white cards which they are greyed out because you're the judge. It would be nice if they were actually hidden or if there was an option to hide them when it's your turn since they don't bear any relevance to the current round. I've tried to select greyed cards more than once before I realized I'm meant to be judging!

**Comment by Lattyware** [comment]
I've made they "greying out" a little more pronounced, hopefully that helps, along with the recent update with changing the shadow colour when cards are "active". Ideally hiding them totally wouldn't be necessary as it's often nice to look at your hand while you wait.

I'd rather not implement an option for this, as it's a very small, specific thing and it feels quite niche, unless I get a lot of feedback otherwise.

With that said, if this is something you feel strongly about, it is extremely easy to do this with an custom style or ad-blocker—you would want to target elements with the `.hand.not-playing` classes for removal.
