### ISSUE TITLE
Discarding 1st Card During Pick 2 Breaks Play

### ISSUE THREAD

**Issue by aforestgrew** [Lattyware/massivedecks#155]
If someone discards their first card during a Pick 2+ round, the card doesn't get de-selected and the player is unable to re-select a new 1st card. They end up needing to be skipped to continue the game.

**Comment by Lattyware** [comment]
OK, yeah, I managed to reproduce this, this is a bug. The card is still a part of the pick even though it is no longer in the player's hand, which results in the slot being filled with nothing.

As a note, a slightly better work-around rather than skipping the player is to have them refresh the page in their browser: this should clear the pick and fix it, allowing them to play.
