### ISSUE TITLE
Client will not connect to Server

### ISSUE THREAD

**Issue by consolecwby** [Lattyware/massivedecks#156]
I am trying to launch this on docker with a synology nas.
I am unable to use the docker-compose so i am just trying to launch each image separately.
I have other services running on ports 80 and 8080 so i have to use different ports for the client and server app. 
The ports are probably my issue. 
I can connect to the client at what i substituted for 8080 but it does not work because it cant find server. 
Any ideas on how to get this to work?

**Comment by Lattyware** [comment]
This should be entirely possible, if you can access the client it should proxy requests to the server, so the issue must be the internal link between the server and client.

The nginx server looks for `server:8081`, so that will need to resolve for it to work. This is normally set up with an internal docker network (so the server is isolated—this means that it shouldn't need the port changing as it can't overlap with anything else). So the first thing I'd check is if [the internal bridge network](https://docs.docker.com/network/bridge/) is set up and both client and server containers are on it. If that is the case, then the next potential problem is the name: the default setup assumes the name `server` and uses Docker's DNS provided by that internal network, which will only work if that is the name of the container. If this isn't true, you can either recreate it with that name, or change the config to use the correct name for the server.

Hope that helps, if not, then please give a bit more detail on how you have it configured (ideally showing the commands you used to create the containers and set it up, the config you have modified, etc...) and I'll be able to give more specific help.

**Comment by consolecwby** [comment]
From what i can tell they are setup in the bridge network. 
root@HouseNetServer:~# docker network inspect bridge
[
    {
        "Name": "bridge",
        "Id": "5bfd6cb0d7bc74ddf3e88482da25e97e290a6bba991830f5e4af585bdade9e4b",
        "Created": "2020-07-10T10:49:50.439332692-05:00",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.17.0.0/16",
                    "Gateway": "172.17.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "1ca5cc16ce1fb447da41d6595e30d2e7c2ff3aba5829d3e1a3ac7d107d716699": {
                "Name": "server",
                "EndpointID": "4631e84ff25b8486bef55499a17a549a1f56d2b8738a5712f076dc3ee0a4ee63",
                "MacAddress": "02:42:ac:11:00:03",
                "IPv4Address": "172.17.0.3/16",
                "IPv6Address": ""
            },
            "324bda44c0ba7f9c8d538046c65a098ca9b78b5628bf75cf0da9045ed7ca9b95": {
                "Name": "linuxserver-heimdall1",
                "EndpointID": "69fc56f6c55d2dcfd1c223a330a5c00896e14abc215475c83abc04dc72167bf6",
                "MacAddress": "02:42:ac:11:00:04",
                "IPv4Address": "172.17.0.4/16",
                "IPv6Address": ""
            },
            "b2be4144cc526bd2a653cec5c2f5b4ff28a751fc3905f02370207d349908e25f": {
                "Name": "linuxserver-smokeping",
                "EndpointID": "2ca22704a49ab400e5e83c66ea0b86a983b271fd645961ce92ae8dd1f0772067",
                "MacAddress": "02:42:ac:11:00:05",
                "IPv4Address": "172.17.0.5/16",
                "IPv6Address": ""
            },
            "baf16be62db3cde81a449d6e56d68ea08e4e2485796935bbcaf2f4e54b66e4ad": {
                "Name": "linuxserver-grocy1",
                "EndpointID": "5477a51ffa7e7ce1c5208b3f1e0515a3ed1995e219a0679143bbb99bc87ccf22",
                "MacAddress": "02:42:ac:11:00:06",
                "IPv4Address": "172.17.0.6/16",
                "IPv6Address": ""
            },
            "ce352bc5a1b508ff740e4fdf3234cc3bfcb5d0db442230ae98b2c4003e6c3648": {
                "Name": "transmission-openvpn-syno",
                "EndpointID": "69fb5fafcd5d82c5c511fffc3f2027274254d7979db24375e0b8fb5059b6b36e",
                "MacAddress": "02:42:ac:11:00:02",
                "IPv4Address": "172.17.0.2/16",
                "IPv6Address": ""
            },
            "f3dbc05f9126687cc698b267d9cc0265219ef7381e513950de7a136dfcc3e32a": {
                "Name": "client",
                "EndpointID": "97409972e359065e45d1a6bc393a2b338c427936bfd25e4d088dee8dec38ddff",
                "MacAddress": "02:42:ac:11:00:07",
                "IPv4Address": "172.17.0.7/16",
                "IPv6Address": ""
            }
        },
        "Options": {
            "com.docker.network.bridge.default_bridge": "true",
            "com.docker.network.bridge.enable_icc": "true",
            "com.docker.network.bridge.enable_ip_masquerade": "true",
            "com.docker.network.bridge.host_binding_ipv4": "0.0.0.0",
            "com.docker.network.bridge.name": "docker0",
            "com.docker.network.driver.mtu": "1500"
        },
        "Labels": {}
    }
]

So i pulled the images trying both tagged versions as latest and 2.3.
I go ssh into the server and get root 
then i use the following to launch the image
`docker container run --name server massivedecks/server` 
i then repeat for the client but use my alternative ports
`docker container run --name client -p 9730:8080 -p 9720:80 masivedecks/client `

**Comment by Lattyware** [comment]
The issue here is you are using the default `bridge` network, which doesn't provide DNS resolution for legacy reasons in Docker. You could hack around this, but the best option for a number of reasons is to set up a network just for MD (which has the advantage that it isolates MD from your other containers, which is best for security both ways).

Doing something like `docker network create md` and then `docker network disconnect bridge server`,`docker network connect md server`, etc... (or just specify `--network md` when creating the containers) should make it work (you will probably have to restart the container as well, I'd assume).

As a side note, you only need to bind one port (8080, which is what the nginx server on the client is bound to) externally, so the `9720:80` binding there won't do anything (but shouldn't cause any problems either).

In general, you also probably want to run the server with some environment variables set (`NODE_ENV=production` and `MD_SECRET` with a secret via `npm run generate-secret`).

**Comment by consolecwby** [comment]
That got it thankyou.

**Comment by hutch0** [comment]
Why is it possible to change the port, but not the server name with an environment variable? The real issue here is the server name is opinionated. I've never seen such a thing.

**Comment by Lattyware** [comment]
> Why is it possible to change the port, but not the server name with an environment variable? The real issue here is the server name is opinionated. I've never seen such a thing.

@hutch0 I think you are misunderstanding the architecture of what is going on here. The server name is not defined by the application, the server name is set by Docker and utilised by nginx if you use the standard deployment set up, you can use any name you want, and any front end HTTP server you want, and configure them to find each other however you want. It all has literally nothing to do with the application and is down to docker/nginx, or whatever you use.

**Comment by hutch0** [comment]
I'm sorry for presuming then. I kept trying to get it working, but Nginx inside the container kept throwing errors because it's looking for specifically "server" and I renamed the containers. I couldn't find any way to get it to look for the proper server name.

**Comment by Lattyware** [comment]
> I'm sorry for presuming then. I kept trying to get it working, but Nginx inside the container kept throwing errors because it's looking for specifically "server" and I renamed the containers. I couldn't find any way to get it to look for the proper server name.

You can follow the official advice for the nginx docker container at https://hub.docker.com/_/nginx to mount a different configuration file with the values you like—see the "Complex configuration" section. You can see the default file the container uses at [client/nginx.conf](https://github.com/Lattyware/massivedecks/blob/main/client/nginx.conf#L51).
