### ISSUE TITLE
Card randomization allows duplicates

### ISSUE THREAD

**Issue by TheChilliPL** [Lattyware/massivedecks#183]
I feel the cards should be randomized like in Tetris, so a card can't be given to two players unless there's no other choice (e.g. not enough cards), but today I encountered this:
![image](https://user-images.githubusercontent.com/18823939/95380682-60d56f00-08e7-11eb-8ab1-3324cee74890.png)
I'm sure it's not a duplicate in the deck, I checked it. It happened during testing the deck with Rando Cardrissians (bots)

**Comment by TheChilliPL** [comment]
Huh, the second time now
![image](https://user-images.githubusercontent.com/18823939/95380879-a8f49180-08e7-11eb-97d8-a9ba71c2196b.png)

**Comment by Lattyware** [comment]
Yeah, we definitely don't intentionally duplicate cards. The likely root of this is a card being discarded twice for some reason.

**Comment by TheChilliPL** [comment]
After that I even got the same card placed twice in a pick 3 black card, by the same bot, so either I have not enough cards (I don't think that's the problem) or there is some bug making that happen

**Comment by TheChilliPL** [comment]
![image](https://user-images.githubusercontent.com/18823939/95665900-bebabe80-0b54-11eb-97f4-f2ce961c3ac9.png)

**Comment by Lattyware** [comment]
Yeah, I took a look and I believe the issue is we are both discarding plays [when we have finished playing](https://github.com/Lattyware/massivedecks/blob/4639cd4607fe690545bc3d0231151a7127404338/server/src/ts/timeout/finished-playing.ts#L55), and also [at the start of the new round](https://github.com/Lattyware/massivedecks/blob/4639cd4607fe690545bc3d0231151a7127404338/server/src/ts/games/game.ts#L258).

We should only be doing that in the second case if we are ending the previous round early for some reason (e.g: Czar leaves), and never got to discarding the cards. Instead we do it every time so we duplicate the cards.

**Comment by TheChilliPL** [comment]
Wouldn't discarding plays always at the start of a new round work?

**Comment by Lattyware** [comment]
I believe this has been fixed at some point, please open a new issue if this is still present.
