### ISSUE TITLE
Security Bug Reporting

### ISSUE THREAD

**Issue by ApprenticeofEnder** [Lattyware/massivedecks#365]
## Describe the bug
Please copy and paste or screenshot any error you received.

Hi, I've taken a look through the code upon discovering the game and identified a potential security flaw. Is there a secure channel through which I can report and discuss this?

## How to reproduce the bug
Steps to reproduce the behaviour:
1. Start a new game
2. Enable a particular setting
3. …

**Comment by Lattyware** [comment]
Sure, you can email me at gareth@lattyware.co.uk, you can find my GPG public key (92A57AA673039A4491E6D80E5BDD8CFCA5F0551E) at https://keybase.io/latty to encrypt your message.

**Comment by ApprenticeofEnder** [comment]
Thank you very much! I'll be in touch soon.

**Comment by Lattyware** [comment]
OK, this got discussed via email, so for context: I've determined this isn't a security risk. It related to game code secrecy, which isn't a primary goal for the project, while it could be improved, it at worst means someone joining your game when you don't want them to, which is annoying rather than a big problem, and can be solved using a game password.

I appreciate the report though, and it'd be nice to improve this at some point, just not a focus now. For now I'll close this issue.
