### ISSUE TITLE
invalid JSON issue (output log attached)

### ISSUE THREAD

**Issue by ghost** [Lattyware/massivedecks#66]
I was running for the first time when I got the following error after clicking "Try clicking here to add the Cards Against Humanity base set."

The response received from the server was incorrect: Given an invalid JSON: Unexpected token < in JSON at position 0

Application Info:
	Version: Not Specified
	URL: http://127.0.0.1:9000/

STDOUT from activator: 
       - application - General SSLEngine problem

Output from test

           The game should
Total for specification GameSpec
Finished in 0 ms
0 example, 0 failure, 0 error
LobbySpec
    The lobby should
Total for specification LobbySpec
Finished in 0 ms
0 example, 0 failure, 0 error
PlayersSpec
    The players controller should
      + Not allow new players with the same name as an existing one
      + Notify all clients when a new player joins
      + Validate a valid secret
      + Not validate a secret for a player that doesn't exist
      + Not validate a secret where the secret is wrong
      + Adding an AI should never result in a name clash
      + Adding an AI should notify all clients
Total for specification PlayersSpec
Finished in 35 ms
7 examples, 0 failure, 0 error
Passed: Total 28, Failed 0, Errors 0, Passed 28

See screenshot below. 

![screen shot 2016-12-15 at 2 06 42 pm](https://cloud.githubusercontent.com/assets/10645833/21238108/b9c5f902-c2cf-11e6-9550-abf17024939b.png)

**Comment by Lattyware** [comment]
So the issue in the client is because the server is returning HTML (an error page, presumably) instead of the JSON it expects.

Based on the output from activator you gave, it's an SSL issue - it's probably that the CardCast server that hosts the decks has[ a certificate your system is rejecting](https://stackoverflow.com/questions/13078226/java-sslhandshakeexception-general-sslengine). The JVM uses a  different certificate store to your host system one. A [probable fix is listed in the wiki](https://github.com/Lattyware/massivedecks/wiki/Troubleshooting).

If that doesn't fix your problem, I'd try and get more output from the activator - is there a stack trace with that error?

**Comment by Lattyware** [comment]
This is no longer relevant as of 2.0.
