### ISSUE TITLE
Add option to choose TTS language

### ISSUE THREAD

**Issue by dumbdumb** [Lattyware/massivedecks#68]
default is en-gb i think. can you add a dropdown menu to choose language (and tts male/female if available for +options)

ps . offtopic : can someone help me to install a fork of MD in heroku? i tried but i got app error

**Comment by Lattyware** [comment]
Sorry for the slow response, I thought I'd replied to this - this is indeed currently an issue. It was hard-coded due to Chrome choosing weird defaults, IIRC (on English-language set systems it was defaulting to German). A proper configuration for this would indeed be best - the current set up is a hack that is meant to be replaced.

Unfortunately, I haven't had much time for MD recently. If you are able and willing, I would accept a merge request fixing this.

As a hack for your own use on your own version, changing [the hard-coded value](https://github.com/Lattyware/massivedecks/blob/master/public/javascripts/util.js#L42) would be very easy, and may be good enough.

**Comment by Lattyware** [comment]
As to deployment on Heroku, there are a few manual steps you need to configure.

Firstly, you will need to set up the correct buildpacks - you need these three in order:

- https://github.com/ianpurvis/heroku-buildpack-version
- https://github.com/srid/heroku-buildpack-elm
- https://github.com/heroku/heroku-buildpack-scala

Then you will need to set the configuration variables: `MD_HOST`, `MD_PATH` and `MD_PROTOCOL`. These should come together to form the URL for your deployed application. E.g: for the deployment listed in the project README, these are `https` for protocol, `massivedecks.herokuapp.com` for host, and `/` for path.
