### ISSUE TITLE
Fix the issue where I can't get the CardCast deck in the game sometimes.

### ISSUE THREAD

**Issue by DeepMotions** [Lattyware/massivedecks#76]
It happens after recreating a lobby sometimes. Just fix it please, it's annoying.

**Comment by Lattyware** [comment]
I would need more information about what happens here - do you get an error response or does it just try to load forever?

My instinct is this is just CardCast's API being rate limited or temporarily down, as I've had problems with it previously. Some caching might help this.

On another note, this is an open project, so demanding requests are not appreciated - if you really want something done, feel free to contribute or inquire about paying for development time, but otherwise you are requesting someone does something for you for free - generally that is done with a softer tone.
