### ISSUE TITLE
Having trouble compiling, can you please upload a pre-compiled version?

### ISSUE THREAD

**Issue by Benji-Collins** [Lattyware/massivedecks#79]
Compiling with the Heroku button no longer works due to issues with the heroku-elm stuff. Could you please upload a precompiled version? Thanks.

**Comment by Lattyware** [comment]
My guess is this is going to be an issue with Elm 0.19 being released. I'll take a look at a fix.

There is work on a 0.19 version which will come at some point, but it's a way out - at the very least, the websockets library isn't available yet for that version, which the game heavily relies on.

**Comment by Lattyware** [comment]
This appears to be [a known issue upstream on the buildpack](https://github.com/srid/heroku-buildpack-elm/issues/26). Looks like that is unmaintained, so an alternative route would be best (the 0.19 version does indeed work differently, but backporting it probably isn't going to be easy).

If you want a copy of the elm code right now, compiling it manually is an option, but if you want a pre-compiled version, the easiest thing is to grab it from [the hosted instance](https://massivedecks.herokuapp.com/) - just grab [`/javascripts/MassiveDecks.js`](https://massivedecks.herokuapp.com/javascripts/MassiveDecks.js).

**Comment by Benji-Collins** [comment]
I tried deploying the fork I made with the app.json removed (so it doesn't try to compile again) but I still get the same error:
`-----> Source app detected`
`-----> Creating profile.d script`
`       SOURCE_VERSION: 74825ae013f6918cf03d368d32a008448fe3b5c1`
`       Script installed to .profile.d/source_version.sh`
`-----> Elm app detected`
`-----> Retrieving 0.18.0`
`https://s3.amazonaws.com/heroku-buildpack-elm/assets/elm/0.18.0/elm:`
`2018-10-22 23:14:14 ERROR 403: Forbidden.`
` !     Push rejected, failed to compile Elm app.`
` !     Push failed`

Is there any way around this? Are there any detailed/simpled tutorials I could follow for hosting this myself?

**Comment by Lattyware** [comment]
The main application is run via the Play Framework, and they have [a deployment guide](https://www.playframework.com/documentation/2.5.x/Deploying).

Producing a build isn't bad - `sbt clean stage` should product a `target/universal/stage` directory containing everything needed to run the server by running the script in `bin` (`massivedecks` for unix, `massivedecks.bat` for Windows).

In testing this out... the older version of Play is really not in a good state. I found I had to manually go and grab [a 0.13 version of SBT](https://www.scala-sbt.org/download.html), and then specifically run it with Java 8 (it seems to think Java 11 is an old version for some reason).

I ended up having to do `/usr/lib/jvm/java-8-openjdk/jre/bin/java -jar ./sbt/bin/sbt-launch.jar clean stage` to get it to run after extracting that version of SBT into the directory.

This is obviously not ideal, but updating everything to current versions would be a lot of work, so the reality is that it'll get fixed with the new version that should be simpler and up-to-date, but as I say, that won't be out for a while.

**Comment by danielfeloiola** [comment]
Is there any simple fix for this? Or maybe a step by step tutorial?
(sorry for annoying, but i'm kinda a rookie programmer with no experience in elm)

**Comment by Lattyware** [comment]
@danielfeloiola [The answer I gave](https://github.com/Lattyware/massivedecks/issues/79#issuecomment-432030361) is pretty much step-by-step. There is nothing simpler right now for deploying your own version.

The easiest option if you just want to play is to use the public server. Otherwise, I'd recommend waiting for the next version (but that won't be soon).

If someone wants to go through and dedicate the time to fixing it up and updating everything, I'd happily accept pull requests, but I can't justify sinking the time into this myself when the plan is to strip a lot of it out and rework in the new version of Elm and a reduced-complexity Scala environment.
