### ISSUE TITLE
Detailed Install Documentation Needed.

### ISSUE THREAD

**Issue by arcreigh** [Lattyware/massivedecks#82]
I have been trying to figure out how to install this on ubuntu 18.04, In the wiki there are 0 useful steps to anyone who wants to deploy this outside of a link to play2.5's documentation which also does not list how to install this. 
What is my starting point?
What are the Dependencies?
What kind of backend database does this use if any?
Etc.
We do not wish to use heroku as we have an ESXi host which makes deploying VM's super easy.

**Comment by Lattyware** [comment]
Yes, unfortunately the deployment process at the moment is much more awkward than it should be. Both the process being a pain and the documentation being bad will be sorted with the new version which makes a number of core changes, and will have more deployment options including Docker and a much simplified manual deployment process.

If you want to deploy right now, [this issue](https://github.com/Lattyware/massivedecks/issues/79#issuecomment-432030361) has more details. It's a pain at the moment for sure, due to the old versions of the tooling being used. There is no database for this version, and the only dependencies you need to install manually are Elm 0.18 (if you compile the front-end code, as noted in that issue you can just use the pre-compiled version) and the play framework - the rest are managed via SBT through that framework.

In general, yes, it's a known issue and it's being fixed, but not quickly due to time constraints and upstream issues (no websocket support in Elm 0.19).

If you would like to contribute by documenting this process as you go, that would be a great stop-gap for now.

**Comment by arcreigh** [comment]
How far off is the new version?

**Comment by arcreigh** [comment]
heh unfortunately my expertise lies on the network side of things vs the coding world I wish I could help but I would do more harm than good I promise ya that xD. Thank you for the quick replies I do appreciate it and it is good to see the project isn't dead :)
