### ISSUE TITLE
duplicate cards

### ISSUE THREAD

**Issue by konstrain** [Lattyware/massivedecks#85]
I was playing a few rounds when I saw duplicate cards were played.

Application Info:Version: 9b74f7e-devURL: https://massivedecks.herokuapp.com/

**Comment by Lattyware** [comment]
This is expected behaviour, assuming that you had cycled through one of the decks.

When a deck is emptied, it is duplicated and readded (to simulate a reshuffle) and you can end up with the same cards again. Use more/larger decks to avoid this happening.

(The next version of Massive Decks will actually track discarded cards and do a real reshuffle when the decks run out, as in a real game - this will slightly change the behaviour so if you hold a card it won't show up again)

If it is not possible that the deck was cycled, another potential is that the cards are duplicated in the deck, or multiple decks with the same card were added. There is no deduplication of the decks, so this is possible.

If you don't think it is either of these, please let me know - ideally with the deck codes in use if that is possible.
